---
title: "Southwest Airlines Forecasting Final Project-Data Analysis"
format: html
editor: visual
---

### Group Members: Ari, Assmaa, Evan

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(boot)
```

```{r}
# Vector that contains the major airlines that we have data for
airlines = c("Alaska", "American", "Delta", "Frontier", "JetBlue", "Southwest", "Spirit", "United")
months = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
# Now setup the translation vector - essentially a lookup table
names(months) <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
seasons = c("Winter", "Winter", "Spring", "Spring", "Spring", "Summer", "Summer", "Summer", "Fall", "Fall", "Fall", "Winter")
names(seasons) <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
quarter_str = c("Q1", "Q2", "Q3", "Q4")
quarters = c(1,2,3,4)
```

```{r}
# Flights
flights_data = data.frame()
# Looping through our airlines vector to extract the flight data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Flights/",airlines[i],"Flights.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
  # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$MonthName <- months[as.character(df$Month)]
  df$MonthName <- factor(df$MonthName, levels = months)
  df$Season <- seasons[as.character(df$Month)]
  df$Year <- as.integer(gsub(",", "", df$Year))
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$INTERNATIONAL <- as.numeric(gsub(",", "", df$INTERNATIONAL))
  # Append the df dataframe to the flights_data dataframe
  flights_data = rbind(flights_data, df)
}
flights_data %>% filter(Airline == "Southwest")
```

```{r}
# Passengers
passengers_data = data.frame()
# Looping through our airlines vector to extract the passenger data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Passengers/",airlines[i],"Passengers.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
  # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$MonthName <- months[as.character(df$Month)]
  df$MonthName <- factor(df$MonthName, levels = months)
  df$Season <- seasons[as.character(df$Month)]
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$INTERNATIONAL <- as.numeric(gsub(",", "", df$INTERNATIONAL))
  # Append the df dataframe to the passengers_data dataframe
  passengers_data = rbind(passengers_data, df)
}
passengers_data
```

```{r}
# Available Seat Miles
available_seat_miles_data = data.frame()
# Looping through our airlines vector to extract the available seat mile data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Available-Seat-Miles/",airlines[i],"_ASM.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
  # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$MonthName <- months[as.character(df$Month)]
  df$MonthName <- factor(df$MonthName, levels = months)
  df$Season <- seasons[as.character(df$Month)]
  df$Year <- as.integer(gsub(",", "", df$Year))
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$INTERNATIONAL <- as.numeric(gsub(",", "", df$INTERNATIONAL))
  # Append the df dataframe to the flights_data dataframe
  available_seat_miles_data = rbind(available_seat_miles_data, df)
}
available_seat_miles_data 
```

```{r}
# Load Factor
load_factor_data = data.frame()
# Looping through our airlines vector to extract the load factor data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Load-Factor/",airlines[i],"_LoadFactor.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
  # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$MonthName <- months[as.character(df$Month)]
  df$MonthName <- factor(df$MonthName, levels = months)
  df$Season <- seasons[as.character(df$Month)]
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$INTERNATIONAL <- as.numeric(gsub(",", "", df$INTERNATIONAL))
  # Append the df dataframe to the passengers_data dataframe
  load_factor_data = rbind(load_factor_data, df)
}
load_factor_data
```

```{r}
# Net Income
net_income_data = data.frame()
# Looping through our airlines vector to extract the net income data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Net-Income/",airlines[i],"_NI.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
 # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$Quarter <- factor(df$Quarter, levels = quarters)
  df$Year <- as.integer(gsub(",", "", df$Year))
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$LATIN.AMERICA <- as.numeric(gsub(",", "", df$LATIN.AMERICA))
  df$ATLANTIC <- as.numeric(gsub(",", "", df$ATLANTIC))
  df$PACIFIC <- as.numeric(gsub(",", "", df$PACIFIC))
  # Append the df dataframe to the flights_data dataframe
  net_income_data = rbind(net_income_data, df)
}
net_income_data %>% filter(Airline == "United")
```

```{r}
# Operating Revenue
operating_revenue_data = data.frame()
# Looping through our airlines vector to extract the net income data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Operating-Revenue/",airlines[i],"_OR.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
  # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$Quarter <- factor(df$Quarter, levels = quarters)
  df$Year <- as.integer(gsub(",", "", df$Year))
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$LATIN.AMERICA <- as.numeric(gsub(",", "", df$LATIN.AMERICA))
  df$ATLANTIC <- as.numeric(gsub(",", "", df$ATLANTIC))
  df$PACIFIC <- as.numeric(gsub(",", "", df$PACIFIC))
  # Append the df dataframe to the flights_data dataframe
  operating_revenue_data = rbind(operating_revenue_data, df)
}
operating_revenue_data 
```

```{r}
# Revenue Passenger Miles
revenue_passenger_miles_data = data.frame()
# Looping through our airlines vector to extract the load factor data
for(i in 1:length(airlines))
{
  # Making the path to the file for each of the airlines
  airline_file = paste("US-Airline-Revenue-Passenger-Miles/",airlines[i],"_RPM.csv", sep="")
  # Read the file
  df = read.csv(airline_file)
  # Remove the incomplete years from the dataframe
  df <- df %>%
    filter((Year > 2002 & Year < 2020) | (Year > 2022))
  # Make a column for the Airline string
  df["Airline"] = airlines[i]
  df$MonthName <- months[as.character(df$Month)]
  df$MonthName <- factor(df$MonthName, levels = months)
  df$Season <- seasons[as.character(df$Month)]
  df$TOTAL <- as.numeric(gsub(",", "", df$TOTAL))
  df$DOMESTIC <- as.numeric(gsub(",", "", df$DOMESTIC))
  df$INTERNATIONAL <- as.numeric(gsub(",", "", df$INTERNATIONAL))
  # Append the df dataframe to the passengers_data dataframe
  revenue_passenger_miles_data = rbind(revenue_passenger_miles_data, df)
}
revenue_passenger_miles_data
```

```{r}
ggplot(data = passengers_data, aes(x = MonthName, y = TOTAL, group = Year)) + 
    geom_line(aes(color=as.character(Year))) +
    facet_wrap(~Airline) +
    labs(title="Number of Passengers",
        x ="Year", y = "Total") +
    theme( axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.text.x = element_text(angle=90))

```

```{r}
# Annual passengers
annual_pass_data <- passengers_data %>% group_by(Year, Airline) %>% summarize(AnnualPassengers = sum(TOTAL))
annual_pass_data
```

```{r}
grph <- annual_pass_data %>%  
  filter(Year >= 2006 & Year <= 2018) %>%
  ggplot(aes(x = Year, y = AnnualPassengers / 1000000, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title="2006-2018 Annual Passenger Count (millions) - ex-COVID",
        x ="Year", y = "Total") + 
    theme(axis.text.x = element_text(angle=90))

print(grph)
```

```{r}
ggplot(data = flights_data, aes(x = MonthName, y = TOTAL, group = Year)) + 
    geom_line(aes(color=as.character(Year))) +
    facet_wrap(~Airline) + 
    labs(title="Number of Flights",
        x ="Year", y = "Total") +
    theme( axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.text.x = element_text(angle=90))

```

```{r}
passengers_data %>% group_by() %>% ggplot(aes(x = Season, y = TOTAL, group = Year)) + 
    geom_bar(stat="identity", aes(color=as.character(Year))) +
  
    facet_wrap(~Airline) +
    theme(legend.position = "none", axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.text.x = element_text(angle=90)) +
  labs(title = "Passenger Volume by Season")

```

```{r}
# data for June
month_value = 6 
# data for 'Delta'
airline_value = "Delta"

passengers_data %>% filter(Month == month_value ) %>% ggplot(aes(x = Year, y = TOTAL, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title=paste(months[month_value], " Passengers",sep=""),
        x ="Year", y = "Total") + 
    theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.text.x = element_text(angle=90))

```

```{r}
# American @ 2015 : International passengers down because of stronger dollar and rise in oil prices
# Delta @ 2010 : International traffic down because of a decrease of 11% in capacity
# Frontier @ 2006 : Holiday travel system problems
# Frontier @ 2014 : Customer anger over delays and cancellations, low quality score
# JetBlue @ 2005 : Redoing their business model after passengers voiced frustrations over paying high prices for fares and having flights delayed by slowdowns
# Southwest @ 2011 : Slowly recovering from 2008 recession
# Spirit @ 2013 : Lead in passenger complaints among the airline industry
# United @ 2017 : Faced significant negative public attention following the incident involving Dr. Dao on United Flight 3411
# United @ 2021 : Recovering from COVID-19 pandemic 

```

```{r}
# data for June
for (month_value in 1:12) {

grph = passengers_data %>% filter(Month == month_value) %>% ggplot(aes(x = Year, y = TOTAL, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title=paste(months[month_value], " Passengers",sep=""),
        x ="Year", y = "Total") + 
    theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.text.x = element_text(angle=90))
print(grph)
}
```

```{r}
passenger_dataset <- passengers_data %>% select(Year, Month, Airline, TOTAL)
flight_dataset <- flights_data %>% select(Year, Month, Airline, TOTAL)
pass_flight <- inner_join(passenger_dataset, flight_dataset, by = c("Year", "Month", "Airline"), suffix = c(".passengers", ".flights"))
pass_flight$pass_flight_ratio = pass_flight$TOTAL.passengers / pass_flight$TOTAL.flights
pass_flight
```

```{r}
# data for June
for (month_value in 1:12) {

grph <- pass_flight %>% filter(Month == month_value ) %>% ggplot(aes(x = Year, y = pass_flight_ratio, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title=paste(months[month_value], " Passengers per Flight Ratio",sep=""),
        x ="Year", y = "Total") + 
    theme(axis.text.x = element_text(angle=90))

print(grph)
}
```

```{r}
# available seat miles
for (month_value in 1:12) {

grph <- available_seat_miles_data %>% filter(Month == month_value ) %>% ggplot(aes(x = Year, y = TOTAL/1000000, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title=paste(months[month_value], " Available Seat Miles (millions)",sep=""),
        x ="Year", y = "Total") + 
    theme(axis.text.x = element_text(angle=90))

print(grph)
}
```

```{r}
# Load factor
for (month_value in 1:12) {

grph <- load_factor_data %>% filter(Month == month_value ) %>% ggplot(aes(x = Year, y = TOTAL, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title=paste(months[month_value], " Load Factor (%)",sep=""),
        x ="Year", y = "Total") + 
    theme(axis.text.x = element_text(angle=90))

print(grph)
}
```

```{r}
airline_filter1 = c("Frontier", "Spirit")
net_income_data %>% 
  filter((Airline %in% airline_filter1)) %>%
  ggplot(aes(x = Quarter, y = TOTAL/1000, group = Year)) + 
    geom_line(aes(color=as.character(Year))) +
    facet_wrap(~Airline) +
  labs(title="Quarterly Net Income (millions)",
        x ="Quarter", y = "Total") + 
    theme( axis.text.x = element_text(angle=90))
```

```{r}
airline_filter2 = c("Delta", "American", "United")

net_income_data %>% 
  filter((Airline %in% airline_filter2)) %>%
  ggplot(aes(x = Quarter, y = TOTAL/1000, group = Year)) + 
    geom_line(aes(color=as.character(Year))) +
    facet_wrap(~Airline) +
labs(title="Quarterly Net Income (millions)",
        x ="Quarter", y = "Total") + 
    theme( axis.text.x = element_text(angle=90))
```

```{r}
airline_filter2 = c("Alaska", "JetBlue", "Southwest")

net_income_data %>% 
  filter((Airline %in% airline_filter2)) %>%
  ggplot(aes(x = Quarter, y = TOTAL/1000, group = Year)) + 
    geom_line(aes(color=as.character(Year))) +
    facet_wrap(~Airline) +
labs(title="Quarterly Net Income (millions)",
        x ="Quarter", y = "Total") + 
    theme( axis.text.x = element_text(angle=90))
```

```{r}
# Net Income
annual_net_data <- net_income_data %>% group_by(Year, Airline) %>% summarize(AnnualNet = sum(TOTAL))
annual_net_data
```

```{r}
grph <- annual_net_data %>%  
  filter(Year >= 2015) %>%
  ggplot(aes(x = Year, y = AnnualNet / 1000, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title="Net income (millions) since 2015 - ex-COVID",
        x ="Year", y = "Total") + 
    theme(axis.text.x = element_text(angle=90))

print(grph)
```

```{r}
annual_revenue_data <- operating_revenue_data %>% group_by(Year, Airline) %>% summarize(AnnualTotal = sum(TOTAL))
annual_revenue_data
```

```{r}
# Operating revenue 
#for (qtr_value in 1:4) {

grph <- annual_revenue_data %>%  ggplot(aes(x = Year, y = AnnualTotal/1000, group = Airline)) + 
    geom_line(aes(color=Airline)) +
    facet_wrap(~Airline) +
    labs(title="Operating revenue (millions)",
        x ="Year", y = "Total") + 
    theme(axis.text.x = element_text(angle=90))

print(grph)
#}
```

```{r}
# PREDICTION: 

# As shown in the plots above, the operating revenue of each airline is decreasing post-COVID. Additionally, the net income has been decreasing since 2016 for most airlines. Southwest has been in a steady linear decline since 2016 (ex-COVID) and is approaching an annual net income of break even.
# The load factor for Southwest is around 80%. Most of the other domestic carriers, with the exception of Frontier, are around 85%.

# United, American, Delta, with their acquisitions of Continental, US Airways, and Northwest respectively, have increased their passengers and flights significantly, and this is clearly shown in the available seat miles for the acquiring airlines. Southwest, with their acquisition of AirTran in 2011, has increased their passengers and routes by 25%, including the addition of international routes to Caribbean and Mexico. The remaining airlines have seen only modest growth in passengers and flights in the last 20 years.

# For Southwest, starting in the early 2000s, the number of passengers per flight was 75, and has steadiliy increased to the current average of approximately 120-125 passengers per flight. Other airlines are able to get from 150-160 passengers per flight. Frontier is able to get 175 passengers per flight, yet still charge for checked bags and carry-ons, as well as seats. The other airlines also charge for checked bags and seats, which is becoming a revenue generating norm among the US airlines.

# Based on the facts above, we predict that Southwest will see a 15% decline in the short term in the number of passengers due to charging fees when that is the norm for all other airlines. Airlines first started introducing checked bag fees in 2008, likely due to the Great Recession in an attempt to recover revenue lost due to falling passenger numbers. The airlines that introduced the baggage fees saw a 20-30% decline in passengers, however this was also compounded by the Great Recession of 2008. This dip and subsequent steady rise is reflected in the operating revenue plots for each airline. Likewise, Southwest will slowly recover the passengers lost due to fees after about 1 year as passengers start getting used to the fees and return to the airline for the convenience of the routes they are servicing. We predict that in June 2026, the passenger numbers will recover to the May 2025 levels.
```

## Reference Class Forecasting

By Assmaa Aziz

```{r}
#There are uncontrollable factors beyond these policy changes that could influence the number of passengers flying Southwest. Examples of economical factors are inflation, rising costs of needs, increased unemployment, and Trump's tariffs. Examples of political factors are Trump's strict immigration policies and his increase in deportations. 

#Public backlash through social media could amplify negative sentiment and consumers could show their dissatisfaction for these policy changes by boycotting the airline.

#To account for these outside influences, we're using reference classes by comparing Southwest's passenger data to other similar airlines that began charging baggage fees.

#We're looking at other domestic U.S. airlines who are competitors to Southwest and therefore serve a similar customer base.

#JetBlue began charging for checked baggage in 2015.
#Spirit began charging for carry-on bags in 2010.
#Frontier began charging for carry-on bags in 2013.
#Alaska began charging for checked baggage in 2010.

#For each reference class, we are looking at the change in the number of passengers after the implementation of the new policy. If we notice the same trend among all airlines during the same time period, then we can conclude the change is likely due to outside factors and not the policy change. However, if we see a different trend only in the airline with the policy change, we can conclude the effect is likely due to the policy change.

#We'll approximate the change in the number of passengers for each reference class.

#Based on how these changes affected these comparable airlines with similar policy changes, we'll adjust our Fermi estimate.
```

```{r}
passengers_data

passengers_data_refcl = passengers_data %>% filter(Year <= 2024) %>% filter(Airline %in% c('JetBlue', 'Frontier', 'Spirit', 'Alaska', 'Southwest')) %>% select(Year, Month, TOTAL, Airline, MonthName)

passengers_data_refcl_summary = passengers_data_refcl %>% group_by(Airline, Year) %>% summarize(Total = sum(TOTAL))

plot_refcl = ggplot(passengers_data_refcl_summary, aes(x = Year, y = Total, color = Airline)) + geom_line() + geom_vline(xintercept = 2010, linetype = 'dashed') +  geom_vline(xintercept = 2013, linetype = 'dotted') +  geom_vline(xintercept = 2015, linetype = 'dotdash') + labs(title = 'Total Passengers Per Year')

plot_refcl
```

```{r}
#OBSERVATIONS

#Spirit, Alaska
#The policy change occurred in 2010. After 2010, both Spirit and Alaska airlines follow an upward trend. The remaining airlines also follow an upward trend for several years after 2010. The total number of passengers on domestic flights continued to increase for Spirit and Alaska after implementing these changes. This suggests the policy change did not impact passenger volume.

#Frontier
#The policy change occurred in 2013. After 2013, Frontier follows an upward trend. The remaining airlines follow an upward trend for several years after 2013. The total number of passengers on domestic flights continued to increase for Frontier after implementing these changes. This suggests the policy change did not impact passenger volume.

#JetBlue
#The policy change occurred in 2015. After 2015, JetBlue is continues increasing and then begins to flatten out and decline a couple years later, approximately around 2018. At around the same point, Alaska goes from increasing to flattening out, similar to JetBlue's trend in recent years. This suggests the influence of outside factors affecting both JetBlue and Alaska. However this trend is only visible in 1 airline unrelated to policy changes, which suggests the cause is likely something specific to Alaska airlines. The remaining airlines follow an upward trend for several years after 2015. JetBlue declining while other airlines increase suggests that JetBlue's change in baggage policy had a some impact. Since the decline is small and not a significant drop, it suggests the baggage policy had a small impact but ultimately did not dramatically decrease passenger volume.

#In all 3 time periods, Southwest has a significantly higher number of domestic passengers than our reference classes. After each policy change by other airlines, Southwest also experienced a dramatic increase. This suggests that some passengers may have switched over to Southwest after other airlines introduced new baggage fees.

#Overall, we didn't find strong evidence to suggest that implementing new baggage fees leads to a decline in passenger volume. In the budget airlines, Spirit and Frontier, their passenger volume continued to grow after implementing baggage fees. JetBlue experienced a very small decline after the policy change, but nothing large enough to suggest a significant drop in passenger volume. This suggests that implementing baggage fees has a small impact and doesn't hurt demand in the long-term.
```

```{r}
#Percent Change

#Spirit, Alaska 2010
before_2010 = passengers_data_refcl_summary %>% filter(Year == 2009 & (Airline == 'Spirit' | Airline == 'Alaska'))
after_2010 =  passengers_data_refcl_summary %>% filter(Year == 2011 & (Airline == 'Spirit' | Airline == 'Alaska'))

percent_change_2010 = ((after_2010$Total - before_2010$Total)/before_2010$Total)*100

percent_change_2010 = data.frame(airline = before_2010$Airline, percent_change_2010 = percent_change_2010)

percent_change_2010

#Frontier 2013
before_2013 = passengers_data_refcl_summary %>% filter(Year == 2012 & Airline == 'Frontier')
after_2013 = passengers_data_refcl_summary %>% filter(Year == 2014 & Airline == 'Frontier')

percent_change_2013 = ((after_2013$Total - before_2013$Total)/before_2013$Total)*100


percent_change_2013 = data.frame(airline = before_2013$Airline, percent_change_2013 = percent_change_2013)
percent_change_2013

#JetBlue 2015
before_2015 =  passengers_data_refcl_summary %>% filter(Year == 2014 & Airline == 'JetBlue')
after_2015 = passengers_data_refcl_summary %>% filter(Year == 2016 & Airline == 'JetBlue')

percent_change_2015 = ((after_2015$Total - before_2015$Total)/before_2015$Total)*100

percent_change_2015 = data.frame(airline = before_2015$Airline, percent_change_2015 = percent_change_2015)
percent_change_2015

```

```{r}
#2010
#After implementing their new policies, Alaska and Spirit's passenger volumes grew by 14.62% and 36.26% respectively.

#2013
#After implementing the new policies, Frontier's passenger volume grew by 13.09%.

#2015
#After implementing the new policies, JetBlue's passenger volume grew by 19.29%.
#This growth suggests baggage fees do not hurt consumer demand.

#BASE ESTIMATE
#Recall our forecasting question: Will changes to Southwest's policies in May 2025 decrease the total passengers in June 2025 and at the end of the third quarter?

#Because we found that all of our reference classes experienced growth after these policy changes, this suggests that the probability the total passengers will decrease from May 2025 to June 2025 is very low. We estimate this probability to be 0.20. 

#However, Southwest's brand identity is tied to providing free checked bags whereas our reference classes don't have that branding. Southwest has a higher chance of receiving backlash, which increases our estimate to a probability of 0.25.

```

##Influence of Public Opinion

```{r}
#Usinge our base forecast
```

##Weighted Average of Reference Classes and Public Opinion
